### ISSUE TITLE
Cleanup Example Items

### ISSUE THREAD

**Issue by nomadjimbob** [Drustcraft/mythicmobs#3]
The MythicMobs example items need to be cleaned up to follow lore and mob title standards.

The mob title standards are not yet defined, but currently, all mobs titles should be white. The standard should be added to the [Drustcraft Denizen](/drustcraft/denizen) wiki.

A suggestion would be on colours:

* White: Common mobs
* Orange: Rare mobs (<20% spawn rate?) that are 200%+ stronger
* Red: Elite/Boss mobs

**Comment by ProjectHSI** [comment]
updated the repo with the colour scheme, updating wiki

**Comment by ProjectHSI** [comment]
updated the wiki

**Comment by nomadjimbob** [comment]
We should probably define the mob types in the wiki as well (Common/Rare/Elite|Boss) and what that means.

This probably feeds into a world design/matrix page on the wiki to be created like:

| Tier | Range | HP | Armor | Common Mobs | Rare Mobs | Bosses |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | 0-500 | 1-5? | Leather | Vanilla | Tortus? | None |
| 2 | 500-1000 | 3-7 | Iron, Chain? | Vanilla | ?? | Herobrine? |
| 3 | 1000-3000 | ?? | Netherite, Copper | Vanilla? (Increase health?) | ?? | Herobrine? |
| 4 | 3000-4000 | ?? | Ruby? | ?? | ?? | ?? |

(some armour will overlap or be within the same regions, but with different attributes). I guess this makes sure that we have some kinda progression in armour and mobs. Makes sure that we are just not creating tons of overpowering weapons or mobs that are way too hard with no real purpose. It also drives players to keep moving away from spawn to find harder mobs, get and more customized armor/weapons, etc.

We would also need to be careful in such a document and only include the mobs/weapons that we have created in our Repos and not items that we have purchased for the server
